### ISSUE TITLE
func_friction bug

### ISSUE THREAD

**Issue by FlowerShopGuy** [Bots-United/metamod-p#16]
Hello, I use metamod-p (and amxmodx 1.8.2)  on my SVEN COOP server (Windows), and with this metamod-p I have this issue: https://www.youtube.com/watch?v=65Gb-bIgfAE

**Comment by FlowerShopGuy** [comment]
Well... I think no one gonna reply here.

**Comment by p5-vbnekit** [comment]
Does same happen without metamod too?

**Comment by TheStormN** [comment]
This bug is not Metamod-p related.
