### ISSUE TITLE
 Banned for flood connect

### ISSUE THREAD

**Issue by sezekz** [Bots-United/metamod-p#17]
With adminslots.amxx enable
amx_reservation 1
amx_hideslots 0
If i try to connect without slot flag when the server is full (31/32)
trying like 10 consecutive connect and "You have been banned from this server."
And is banned permanently...
Someone known why? ...

**Comment by R4to0** [comment]
I'm sure this has nothing to do with this repository. If you need help regarding AMXX issues, go ask in their site at https://forums.alliedmods.net/

**Comment by jkivilin** [comment]
Closing, unrelated to metamod-p.

**Comment by sezekz** [comment]
> I'm sure this has nothing to do with this repository. If you need help regarding AMXX issues, go ask in their site at https://forums.alliedmods.net/

Yeah... alliedmodders told me "Reunion is not supported in this website. You should ask for support in the site you got the plugin from." and all i found about rehlds support is that site, sorry if is the wrong direction :D have any advice where i can search? ...
