### ISSUE TITLE
Freezes on load with latest Steam CS 1.6 on Linux

### ISSUE THREAD

**Issue by sjain882** [Bots-United/metamod-p#20]
it just freezes when it finishes loading a new game for me on a client, all im doing is adding the line
 `gamedll_linux "addons/metamod/dlls/metamod.so"` 
to liblist.gam. The metamod.so is the latest metamod-p from github. It doesnt matter where i put that line, it always freezes.

I tried it with ReGameDLL_CS, but then it crashes to desktop, even earlier in the loading stages

this is on a full fresh install of HL + CS

] version

Protocol version 48

Exe version 1.1.2.7/Stdio (cstrike)

Exe build: 19:53:35 Aug  3 2020 (8684)

**Comment by jeefo** [comment]
It's normal. Don't use metamod-p on listen server under Linux.
