### ISSUE TITLE
Fucntion 'Server_GetBlendingInterface' not found, causing the server to crash

### ISSUE THREAD

**Issue by DarthMan** [Bots-United/metamod-p#22]
Hello there. Not sure if this issue is only TFC related, but whenever metamod tries to look for the signature of Server_GetBlendingInterface my server crashes. Either the function does not exist, or the pointer to it from memory is invalid (bad signature).

Below I attached the debug error:

```L 09/05/2021 - 16:11:29: [META] (debug:6) Couldn't find Server_GetBlendingInterface in game DLL 'tfc': function not found```

**Comment by ShootingKing-AM** [comment]
A test plugin please? And a way to reproduce the issue?

**Comment by DarthMan** [comment]
I don't know how to reproduce it, and I don't think it's caused by any plugins, but by metamod itself.

**Comment by DarthMan** [comment]
![meta list](https://user-images.githubusercontent.com/10210302/133244755-d4587fce-5dcb-4191-8443-4922a8d3cdb0.png)

**Comment by DarthMan** [comment]
![meta amxx](https://user-images.githubusercontent.com/10210302/133244865-bad5b366-1bbe-42aa-bf0f-73792f801bac.png)

OS: Windows Server 2019

**Comment by ShootingKing-AM** [comment]
> I don't know how to reproduce it, and I don't think it's caused by any plugins, but by metamod itself.

Then remove all plugins (simply rename metamod's plugins.ini) still it crashes ?

**Comment by DarthMan** [comment]
Oh yep, it's not metamod-p right now, as Is witched to metamod due to that error. Also, problem is, issue can happen anytime, in seconds, in minutes, in hours. So maybe I test with no plugins but I have to play for like 4 hours continuously tot rigger that issue, it only happens when there are people actually playing.

**Comment by DarthMan** [comment]
But as the error says, it fails to find the function so all that's needed is a change in metamod to get the proper pointer in memory, since the debug tells me that the issue is coming from metamod directly.

**Comment by TheStormN** [comment]
`Server_GetBlendingInterface` is not defined by all MODs. Actually it is defined only by very few and only produced by Valve's MODs.
You are observing `debug` logs, which are useful only to developers which would have better visibility on different stages during runtime, but this does not mean that they are errors.

Basically, this is not an error and is not the cause of your crashes.

**Comment by DarthMan** [comment]
Unsure then, but I'm guessing that I could have a memory leak somewhere. I see certain natives from certain functions being called when they shouldn't, I had for example a native that checks for valid admin being called from within a function, function that is only called when an admin executes that command, but nobody executed that command on that date (including myself), yet, code from it was called (it is a register_concmd).
Or could be related to this error, maybe?

```L 11/28/2021 - 16:18:52: [META] ERROR: Plugin didn't set meta_result: semiclipex_amxx.dll:ServerDeactivate_Post()```

**Comment by TheStormN** [comment]
You may have many problems with 3rd party plugins, but this is unrelated to Metamod.
